name: repo events

on:
    push:
    pull_request:
        types: [opened, assigned, reopened]


jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3