name: pr comment request
on:
    pull_request_target:
        types: [opened]
    

jobs:
    pr-commits:
        runs-on: ubuntu-latest
        steps:
            - name: comment a new pr
              uses: actions/github-script@v6
              with:
                script: |
                    github.rest.issues.createComment{{
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: context.issue.number,
                      body: 'thanks for contribution',
                    }};