name: workflow a

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: check out code
              uses: actions/checkout@v3

            - name: Run some tasks
              run: echo "Running workflow a tasks"