name: working dirs & shells
on: [push]
defaults:
    run:
        shell: bash

jobs:
    display-working:
        runs-on: ubuntu-latest
        steps:
            - name: display working directory and list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

    display-working-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh

        steps:
            - name: display working directory and list files
              run: |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE